/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.engcia;
// package must be defined in packages from kmodule.xml file

//list any import classes here.
import org.engcia.cf.model.Evidence;
import org.engcia.cf.model.Hypothesis;
import org.engcia.cf.model.Conclusion;

//declare any global variables here

query "Conclusions"
	$conclusion : Conclusion()
end

rule "r1"
	when
		Evidence(bloodEar == "yes" )
	then
		Hypothesis h = new Hypothesis("upper type");
		insert(h);
end

rule "r2"
	when
		Evidence(bloodEar == "no" )
	then
		Hypothesis h = new Hypothesis("lower type");
		insert(h);
end

rule "r3"
	when
		Hypothesis( description == "upper type")
		Evidence(earAche == "yes")
	then
		Conclusion c = new Conclusion(Conclusion.OTORRHAGIA);
		insert(c);
end

rule "r4"
	when
		Hypothesis( description == "upper type")
		Evidence(deafness == "yes")
	then
		Conclusion c = new Conclusion(Conclusion.OTORRHAGIA);
		insert(c);
end

rule "r5"
	when
		Hypothesis( description == "upper type")
		Evidence(cerebrospinal == "yes")
	then
		Conclusion c = new Conclusion(Conclusion.SKULL_FRACTURE);
		insert(c);
end

rule "r6"
	when
		Hypothesis( description == "lower type")
		Evidence(bloodNose == "yes")
	then
		Conclusion c = new Conclusion(Conclusion.EPISTAXE);
		insert(c);
end

rule "r7"
	when
		Hypothesis( description == "lower type")
		Evidence(bloodMouth == "yes", bloodBrown == "yes", vomiting == "yes")
	then
		Conclusion c = new Conclusion(Conclusion.HEMATHESE);
		insert(c);
end

rule "r8"
	when
		Hypothesis( description == "lower type")
		Evidence(bloodMouth == "yes", bloodBrown == "no", vomiting == "no")
	then
		Conclusion c = new Conclusion(Conclusion.MOUTH_HAEMORRHAGE);
		insert(c);
end

rule "r9"
	when
		Hypothesis( description == "lower type")
		Evidence(bloodVagina == "yes")
	then
		Conclusion c = new Conclusion(Conclusion.METRORRHAGIA);
		insert(c);
end

rule "r10"
	when
		Hypothesis( description == "lower type")
		Evidence(bloodPenis == "yes")
	then
		Conclusion c = new Conclusion(Conclusion.HEMATURIA);
		insert(c);
end

rule "r11"
	when
		Hypothesis( description == "lower type")
		Evidence(bloodAnus == "yes", bloodCoffee == "yes")
	then
		Conclusion c = new Conclusion(Conclusion.MELENA);
		insert(c);
end

rule "r12"
	when
		Hypothesis( description == "lower type")
		Evidence(bloodAnus == "yes", bloodCoffee == "no")
	then
		Conclusion c = new Conclusion(Conclusion.RECTAL_BLEEDING);
		insert(c);
end

rule "unknown"
	when
		not Conclusion()
	then
		Conclusion c = new Conclusion(Conclusion.UNKNOWN);
		insert(c);
end

